#!/usr/bin/env python
# -*- mode: python; -*-
# (c) 2011-2013 Adam Stokes <hackr@cypherbook.com>

import os
import sys

commons = {}
commons['script_location'] = os.path.abspath(os.path.dirname(__file__))

sys.path.insert(0, commons['script_location'])

# Cage location is available, import application specifics

if __name__=="__main__":
    from app.system.interface import RunApp
    sys.exit(RunApp(commons).run())
